---
title: "Washington Middle Housing Bill Dashboard (2023)"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 5 
      bootswatch: default
    orientation: columns
    vertical_layout: fill
runtime: shiny
---
 

```{r setup, include=FALSE}
library(flexdashboard)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
thematic::thematic_rmd()

library(shiny) 
library(plotly)
library(leaflet)
library(tidyverse)
library(sf)
library(ragg)
# library(highcharter)

options(shiny.useragg = TRUE)

```

Sidebar {.sidebar}
=======================================================================

<br>

```{r}
tags$br()
# Define inputs
selectInput('model_name', 
            label = 'Select model:', 
            choices = rownames(mtcars), 
            selected = rownames(mtcars)[1])

sliderInput('mpg', 
            label = 'MPG', 
            min = round(min(mtcars$mpg),1e-2), 
            max = round(max(mtcars$mpg),1e-2), 
            value = round(mean(mtcars$mpg),1e-2),  
            step = 1)

sliderInput('sampleSize', 'Sample Size', min=1, max=nrow(diamonds),
            value=min(1000, nrow(diamonds)), step=500, round=0)
```

First Draft 
=======================================================================

Column {data-width=600}
-----------------------------------------------------------------------

### Map

```{r}
leaflet::renderLeaflet(
  leaflet::leaflet() |> addProviderTiles('CartoDB.Positron')
  )
```


Column {data-width=200}
-----------------------------------------------------------------------

### Chart C

```{r}
renderPlot(ggplot2::qplot(mtcars$mpg))
```

### Chart D

```{r}
renderPlot(ggplot(mtcars) +
  aes(x = mpg, y = disp, color = gear, size = gear) +
  geom_point(alpha = .75)) 
```



Column {data-width=200}
-----------------------------------------------------------------------

### Chart E

```{r}
renderPlot(ggplot2::qplot(mtcars$mpg))
```

### Chart F

```{r}
renderPlot(ggplot(mtcars) +
  aes(x = mpg, y = disp, color = gear, size = gear) +
  geom_point(alpha = .75)) 
```


About
===========================
<br>
This is the about page.
